version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
  phpfpm:
    image: triplom/phpfpm-app:0.2.2
    restart: unless-stopped
    networks:
      - app-tier
    env_file:
      - .env

  nginx:
    image: bitnami/nginx:1.25
    restart: unless-stopped
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '8080:8080'
    volumes:
      - ./app/server_blocks:/opt/bitnami/nginx/conf/server_blocks

  mariadb:
    image: bitnami/mariadb:11.2
    restart: unless-stopped
    networks:
      - app-tier
    env_file:
      - .env
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  mariadb_data:
    driver: local
