apiVersion: v2
name: php-app
description: Helm chart deploying a PHP-FPM application with Nginx reverse proxy and MariaDB database
type: application
version: 0.2.0
appVersion: "0.2.2"

maintainers:
  - name: triplom

dependencies:
  - name: mariadb
    version: ">=11.0.0 <12.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mariadb.enabled
