version: '2'

networks:
  app-tier:
    driver: bridge

services:
  phpfpm:
    image: triplom/phpfpm-app:0.1.0
    networks:
      - app-tier
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '8100:80'
      - '8443:443'
    volumes:
      - ./vhosts:/bitnami/nginx/conf/vhosts
  mariadb:
    image: bitnami/mariadb:latest
    environment:
        #   Initial testing values 
        - MARIADB_USER=test
        - MARIADB_PASSWORD=test
        - MARIADB_DATABASE=test
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier