apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
